# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.quest:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.projects"
              label: 'Квесты'
    app.admin.photo:
        class: AppBundle\Admin\ProjectPhotoAdmin
        arguments: [~, AppBundle\Entity\ProjectPhoto, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'Фото'
    app.admin.stage:
        class: AppBundle\Admin\StageAdmin
        arguments: [~, AppBundle\Entity\Stage, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
#              group: "app.admin.group.projects"
#              label: 'Этапы'
    app.admin.review:
        class: AppBundle\Admin\ReviewAdmin
        arguments: [~, AppBundle\Entity\Review, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.projects"
              label: 'Отзывы'
    app.admin.about:
        class: AppBundle\Admin\AboutAdmin
        arguments: [~, AppBundle\Entity\About, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.about"
              label: 'О компании'
    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.about"
              label: 'Клиенты'
    app.admin.teammate:
        class: AppBundle\Admin\TeammateAdmin
        arguments: [~, AppBundle\Entity\Teammate, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.about"
              label: 'Команда'
    app.admin.order:
        class: AppBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.orders"
              label: 'Заявки'
