# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.quest:
        class: AppBundle\Admin\QuestAdmin
        arguments: [~, AppBundle\Entity\Quest, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.quests"
              label: 'Квесты'
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.quests"
              label: 'Категории'
