# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.quest:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.projects"
              label: 'Квесты'
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.projects"
              label: 'Категории'
    app.admin.photo:
        class: AppBundle\Admin\ProjectPhotoAdmin
        arguments: [~, AppBundle\Entity\ProjectPhoto, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.projects"
              label: 'Фото'
